# Generated by Django 4.1.2 on 2022-10-04 11:32

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountAvailable', models.IntegerField(validators=[product.models.Product.validate_amount])),
                ('cost', models.IntegerField()),
                ('productName', models.CharField(max_length=256)),
                ('sellerId', models.IntegerField()),
            ],
        ),
    ]
