# Generated by Django 4.1.2 on 2022-10-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='deposit',
            field=models.IntegerField(choices=[(5, 5), (10, 10), (20, 20), (50, 50), (100, 100)], default=0),
        ),
    ]
