# Generated by Django 4.1.2 on 2022-10-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='deposit',
            field=models.IntegerField(default=0),
        ),
    ]
